--CREACION DE LA TABLA 'Asistente' PARA EL FORMULARIO 

CREATE TABLE Asistente(
	ID_Asist INT NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(100) NOT NULL,
	Email VARCHAR(150) NOT NULL,
	Empresa VARCHAR(100) NOT NULL,
	Tipo VARCHAR(20) NOT NULL,

	PRIMARY KEY (ID_Asist)
);